name: forestapp
regions:
  - aws/us-east-1
services:
  - name: main-api
    type: web
    git:
      repository: github.com/BretMeraki/ForestFInal
      branch: main
    build:
      builder: buildpacks
    ports:
      - port: 8000
        protocol: http
    routes:
      - path: /
        port: 8000
    envs:
      - key: PORT
        value: 8000
    entrypoint: uvicorn forest_app.core.main:app --host 0.0.0.0 --port 8000
    scaling:
      min: 1
      max: 1

  - name: debug-api
    type: web
    git:
      repository: github.com/BretMeraki/ForestFInal
      branch: main
    build:
      builder: buildpacks
    ports:
      - port: 8080
        protocol: http
    routes:
      - path: /debug
        port: 8080
    envs:
      - key: PORT
        value: 8080
    entrypoint: python debug_suite/flask_api/flask_dashboard.py
    scaling:
      min: 1
      max: 1
